### ISSUE TITLE
DIMR config has invalid control element for a single component model

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#127]
Unit test `test_from_scratch_docker()` produces an invalid dimr_config.xml file:
```
<?xml version="1.0" encoding="utf-8"?>
<dimrConfig xmlns="http://schemas.deltares.nl/dimr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.deltares.nl/dimr http://content.oss.deltares.nl/schemas/dimr-1.3.xsd">
  <documentation>
    <fileVersion>1.3</fileVersion>
    <createdBy>hydrolib-core 0.1.3</createdBy>
    <creationDate>2021-11-01 19:28:06.141447</creationDate>
  </documentation>
  <control/>
  <component name="test">
    <library>dflowfm</library>
    <workingDir>.</workingDir>
    <inputFile>test.mdu</inputFile>
  </component>
</dimrConfig>
```
The empty `<control/>` is wrong. The correct element should be:
```
  <control>
    <start name="test"/>
  <control/>
```

**Comment by BeardedPlatypus** [comment]
@arthurvd if I understand this issue correctly, this has to do with the control element, which has the following xsd definition
```xsd
	<xs:complexType name="dimrControlXML">
		<xs:annotation>
			<xs:documentation>Control flow specification for the DIMR-execution. Executed sequentially, except for components in a "parallel" element</xs:documentation>
		</xs:annotation>
		<xs:choice maxOccurs="unbounded">
			<xs:element name="parallel" type="dimr:dimrParallelXML">
				<xs:annotation>
					<xs:documentation>Specification of a control flow that has to be executed in parallel</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="start" type="dimr:dimrComponentOrCouplerRefXML">
				<xs:annotation>
					<xs:documentation>Reference to the component instance to be started</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>
```

If I read this correctly, we can have either `parallel` or `start` elements within the `Control` group. There should be at least one (given that the default of minOccurrences is 1) and an unbounded maximum. Is this correct?

If it is, then the following model is not correct:

```python
class Control(BaseModel):
    """
    Control flow specification for the DIMR-execution.

    Attributes:
        parallel: Specification of a control flow that has to be executed in parallel.
        start: Reference to the component instance to be started.
    """

    parallel: Optional[List[Parallel]] = []
    start: Optional[List[ComponentOrCouplerRef]] = []

    @validator("parallel", "start", pre=True)
    def validate_parallel(cls, v):
        return to_list(v)

    def is_intermediate_link(self) -> bool:
        # TODO set to True once we replace Paths with FileModels
        return False
```

we should not have a list of separate list of parallels and start elements but instead the following:

```python
children: Union[List[Parallel], List[ComponentOrCouplerRef]] = [ default_value ]
```

Where the `default_value` is whatever you want the uninitialized value is going to be. If this is correct I can make the adjustments, such that the default behaviour is correct.
A follow up question in this regard would then be, how do we want to validate that the list has at least 1 element, if we can edit the lists after we assign them? Is this a step done separately?

**Comment by BeardedPlatypus** [comment]
In regards to the default value, can we have a DIMR model without any components? If I understand correctly, currently, the default DIMR model, does not have a `Component`, it has an empty list, while it does have a `Control`. In this case, the default model cannot be in a valid state if we always require the `Control` to have at least  one `start` element. I believe if I understand it correctly, we either need to specify that a DIMR model always has at least 1 component (which would make the defaults different, not sure how that is currently implemented), or the Control should be null if there are no components (and added when the components become non empty). 

Which is the preferred approach?

**Comment by arthurvd** [comment]
Hi @BeardedPlatypus, in response to:

> If I read this correctly, we can have either parallel or start elements within the Control group. There should be at least one (given that the default of minOccurrences is 1) and an unbounded maximum. Is this correct?

No, this is not correct. I've checked the DIMR xsd with the designers, and the current xsd is considered correct. This is the meaning of a control element:
- a ```<control>``` element has at least one child element, possibly more.
- each element may be either a ```<start>```, or a ```<parallel>``` element.
- the meaning of more than one child element inside a control is simply that it is a sequence of "components or couplers" to be run.

Nested inside a ```<parallel>``` element there are exactly one ```<start>``` and one ```<startGroup>```, in either order. This is used for **parallel** execution of "components or couplers" to be run. The ```<startGroup>``` contains the list of parallel task definitions.

But, indeed, the current definition of ```Component.start``` and ```Component.parallel``` is not correct, because their items should be in one list, such that the order is maintained.

**Comment by arthurvd** [comment]
> In regards to the default value, can we have a DIMR model without any components? If I understand correctly, currently, the default DIMR model, does not have a `Component`, it has an empty list, while it does have a `Control`. In this case, the default model cannot be in a valid state if we always require the `Control` to have at least one `start` element. I believe if I understand it correctly, we either need to specify that a DIMR model always has at least 1 component (which would make the defaults different, not sure how that is currently implemented), or the Control should be null if there are no components (and added when the components become non empty).
> 
> Which is the preferred approach?

When serializing, indeed a DIMR model must have a non-empty control element, and as a result also at least one component.
However, when constructing a new DIMR model in memory, prior to serializing, I think the model must be allowed to be empty/incomplete (or handle this via the "prototype" class that you suggested, or maybe better, via some factory method that constructs a DIMR model, given a control/component combination?)

**Comment by arthurvd** [comment]
@evetion : regarding the dimr-1.2.xsd definition for the `<control>` element:
```
		<xs:choice maxOccurs="unbounded">
			<xs:element name="parallel" type="dimr:dimrParallelXML">
# ...
			<xs:element name="start" type="dimr:dimrComponentOrCouplerRefXML">
# ...
		</xs:choice>
```
I googled a bit. One can find conflicting explanations and w3schools.com is a bit inconclusive. Still think that the xsd is correct and defines what is intended:
a control element contains one or more elements, each of which may be either a parallel, or start element.
- I experimented with xml/xsd validation inside XMLSpy, and always got valid input on several test elements.
- Similar explanations on:
  https://xmlzoo.net/xsd/#maxoccurs-on-choice-and-sequence, and
  https://coderedirect.com/questions/550228/xml-schema-maxoccurs-within-choice-element#divid548426
