### ISSUE TITLE
tstart & tstop should be timedelta, not float

### ISSUE THREAD

**Issue by evetion** [Deltares/HYDROLIB-core#129]
These are attributes of the .mdu file in the [time] part. Note that the timedelta could be of days, hours and seconds (another attribuet), so it's not a straightforward type change.

**Comment by priscavdsluis** [comment]
Closing as Won't do: The type for `tstart` and `tstop` are defined as floats in the user manual.
We could consider util functions to get and set these fields with a `timedelta` to help the user.
