### ISSUE TITLE
Limit ini/mdu parsing to most common elements

### ISSUE THREAD

**Issue by evetion** [Deltares/HYDROLIB-core#14]
and ignore multilines or weird comments? See documentation by @priscavdsluis

**Comment by arthurvd** [comment]
Please **do** support these syntax elements:
* Comment character `#` (and don't interpret `;` as comment character).
* Multiple `[sections]` with same name allowed, order should be preserved.
* Order of sections should be preserved in general.
* Keys may have an empty righthandside value (`name =    # comment`).
* Key values may contain any character except for comment character (in particular: also `;` is a valid character).
* Key values in scientific notation should allow `D` (not only `E`) as the exponent character (`UnifFrictCoef = 2.3D-2`). (Case insensitive, `d` and `e` also fine.)

We do **not** directly need to support these rarely used syntax elements:
* Multiline values using line continuation with `\` character
* Quoting of (String) key values using enclosing `#`, e.g.:
  `key = #some value with spaces# # Comment: Not needed for now`


Specific for MDU, not all ini files in general:
* A String key value containing semicolons represents a list of values, typically multiple file names. For recursive parsing it is good to split such kind of values and maintain them as a list.
  Example:
```
[geometry]
FrictFile         = roughness-Main.ini;roughness-Sewer1.ini;roughness-Sewer2.ini
```

**Comment by evetion** [comment]
With regards to the scientific notation with the `D` as in `UnifFrictCoef = 2.3D-2`, we probably could use a validator in Pydantic to quickly rewrite any `D`s in to `E`s. See https://pydantic-docs.helpmanual.io/usage/validators/
