### ISSUE TITLE
Saving and loading a default FMModel should not throw validation errors.

### ISSUE THREAD

**Issue by BeardedPlatypus** [Deltares/HYDROLIB-core#150]
## Expected Behaviour

When creating a new default `FMModel`, saving it to a folder, and then loading it again, I would expect to get a valid model back. 
This behaviour is illustrated in the test provided on the branch: [bug/fmmodel-default-save-load-validation-errors](https://github.com/Deltares/HYDROLIB-core/blob/bug/fmmodel-default-save-load-validation-errors/tests/test_filemodel.py).

**UPDATE Apr 12, 2023:**  Behavior cannot be reproduced anymore. Only added unit test in PR #526 .

## Actual Behaviour

The load step fails due to multiple validation errors:

```
pydantic.error_wrappers.ValidationError: 2 validation errors for FMModel
fm.mdu -> wind -> cdBreakpoints -> 0
  value is not a valid float (type=type_error.float)
fm.mdu -> wind -> windSpeedBreakpoints -> 0
  value is not a valid float (type=type_error.float)
```

See also: [CI jobs](https://github.com/Deltares/HYDROLIB-core/runs/4424218150?check_suite_focus=true)

**Comment by BeardedPlatypus** [comment]
Upon further investigation, this seems to be a problem specific to these two properties, which are not properly parsed as lists of float values.

**Comment by arthurvd** [comment]
Needs re-checking
