### ISSUE TITLE
Add an issue template in the HYDROLIB-core repository

### ISSUE THREAD

**Issue by BeardedPlatypus** [Deltares/HYDROLIB-core#151]
## Expected Behaviour

When creating a new issue in the HYDROLIB-core repository, the issue fields should be populated with a standardised default template to ensure consistent and detailed issues.

For more details about issue templates and how to set them up, see [the github documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)  
For inspiration about possible structures see [this github repository](https://github.com/stevemao/github-issue-templates).

## Actual Behaviour

No issue templates have been set up.

**Comment by evetion** [comment]
Done in https://github.com/Deltares/HYDROLIB-core/commit/b3f1555383a42cd0abe9a28b9b1014ca3c1368e6
