### ISSUE TITLE
Set up SonarCloud integration

### ISSUE THREAD

**Issue by BeardedPlatypus** [Deltares/HYDROLIB-core#17]
- [x]     Verify the settings of the project
- [x]     Ensure code coverage is passed into the sonarcloud configuration
- [x]     Add the badge to the README page
- [x]     Ensure it is added as a pull request check

**Comment by BeardedPlatypus** [comment]
Note that we already have a HYDROLIB-core sonarcloud project, found [here](https://sonarcloud.io/dashboard?id=Deltares_HYDROLIB-core). I think this brings it down to the following tasks:

* Verify the settings of the project
* Ensure code coverage is passed into the sonarcloud configuration
* Add the badge to the README page

**Comment by evetion** [comment]
Fixed by https://github.com/Deltares/HYDROLIB-core/compare/0448fb5cbbafc1aac01046e12332c841c8aa3f58...ee75023728913a060897d3aa37f6ba5e18376bbc
