### ISSUE TITLE
Improve the GitHub landing page.

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#189]
During the [retrospective](https://miro.com/welcomeonboard/YWh5SmxwNXB3WXREODF4ZTljMFRiZzhvQjZlZXdyUkZiZm5lUDRFN2tvSkZvZExBTHJzUDQ5VTdHQkVwaUFHRHwzMDc0NDU3MzQ4NDQ3MjYzMTE3?invite_link_id=993243305306) we talked about improving the landin page for visitors. It is very empty currently. All of our documentation is [here](deltares.github.io/hydrolib-core/), which can be accessed through the about section.

Think about:
- Installation steps
- Basic example(s)
- Contribution
- Feature overview

**Comment by arthurvd** [comment]
Was already done in commit [890bbca](https://github.com/Deltares/HYDROLIB-core/commit/890bbca8edf42620d61c4688fa6fcae390bb0d4d).
