### ISSUE TITLE
Add package information for PyPI-published releases

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#194]
Currently the PyPI page for hydrolib-core states:

> The author of this package has not provided a project description.

**TODO:**
Add package description + url reference.

**Comment by evetion** [comment]
I missed 42c3e15 and have commited 087e0e0. Will only take effect when we make a new (0.3?) release over at pypi, we cannot edit anything there.

**Comment by arthurvd** [comment]
Confirmed that this works correctly now under #280. Closing this issue.
