### ISSUE TITLE
Empty partitionFile field in MDU gives wrong validation error

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#208]
**Describe the bug**
When reading an FMModel where the MDU contains empty partitionFile line, an incorrect validation error occurs ("not a valid dict").

**To Reproduce**
1. Use our base model in 'tests/data/input/e02/f152_1d2d_projectmodels_rhu/c04_DHydamo-MGB-initialisation/fm/',
   the MDU contains this line:
```
PartitionFile                     =                     # Domain partition polygon file *_part.pol for parallel run
```
2. load MDU using:
```python
from hydrolib.core.io.mdu.models import FMModel
modeldir = Path(
    "c:/checkouts/HYDROLIB-core_git/tests/data/input/e02/f152_1d2d_projectmodels_rhu/c04_DHydamo-MGB-initialisation/fm/"
)
mdufile = "moergestels_broek.mdu"

# Read mdu model
fm = FMModel(modeldir / mdufile)
```
2. Running this will produce a validation error:
```
Exception has occurred: ValidationError
1 validation error for FMModel
moergestels_broek.mdu -> geometry -> partitionFile
  value is not a valid dict (type=type_error.dict)
  File "C:\checkouts\HYDROLIB-core_git\hydrolib\core\basemodel.py", line 48, in __init__
    super().__init__(**data)
```

**Expected behavior**
Validation error should not occur, since this field is optional:
```python
    partitionfile: Optional[PolyFile] = Field(None, alias="partitionFile")
```
Possibly this originates from the fact that class PolyFile is involved, most other optional file fields are of type `Optional[Path]`

**Version info (please complete the following information):**
 - OS: Windows (N/A)
 - Version: 0.2.0

**Comment by evetion** [comment]
Can't reproduce with:
```python
def test_special():
    from hydrolib.core.io.mdu.models import FMModel

    fn = test_data_dir / Path(
        "e02/f152_1d2d_projectmodels_rhu/c04_DHydamo-MGB-initialisation/fm/moergestels_broek.mdu"
    )

    # Read mdu model
    fm = FMModel(fn)
    assert fm
```

**Comment by arthurvd** [comment]
Correct diagnosis.
I wonder how we can improve on the error message. The **data contains a list value for the duplicate input (often `[None, None]` if both were empty), but it depends on the Field's datatype what kind of validation error is given.
For example for this field:
```
    waterlevinifile: Optional[Path] = Field(None, alias="waterLevIniFile")
```
the error when passing duplicate lines in input is:
```
geometry -> waterLevIniFile
  value is not a valid path (type=type_error.path)
```

When doing the same for a model class type, e.g.:
```
    crosslocfile: Optional[CrossLocModel] = Field(None, alias="crossLocFile")
    partitionfile: Optional[PolyFile] = Field(None, alias="partitionFile")
```
the error when passing duplicate lines in input is:
```
geometry -> crossLocFile
  value is not a valid dict (type=type_error.dict)

geometry -> partitionFile
  value is not a valid dict (type=type_error.dict)
```

Where can we catch this validation error and improve the message?

**Comment by arthurvd** [comment]
Just noticed this was already reported in #92.

**Comment by arthurvd** [comment]
Duplicate of #92.
