### ISSUE TITLE
Fixed netcdf4 dependency

### ISSUE THREAD

**Issue by hboisgon** [Deltares/HYDROLIB-core#239]
**Describe the bug**
In the pyproject.toml of hydrolib-core, the package version of netcdf4 is fixed. This causes issues when trying to add new packages to your environment (such as hydromt which requires geopandas-gdal-rasterio-fiona-pyproj...). For such GIS packages (and pip install that poetry is using, rather than conda), it is important than dependencies are not too strict (more for developers that want to use hydrolib-core rather than users).

**To Reproduce**
For example just try: poetry add hydromt

**Additional info**
Attached is a pyproject.toml where installation for hydrlolib-core/hydrolib/hydromt is attempted.
[pyproject.zip](https://github.com/Deltares/HYDROLIB-core/files/8814737/pyproject.zip)

**Comment by rhutten** [comment]
@arthurvd  and @evetion, see here our installation problem issue
