### ISSUE TITLE
Validation errors when parsing .mdu file - types of certain keywords need to be changed

### ISSUE THREAD

**Issue by JulienGroenenboom** [Deltares/HYDROLIB-core#240]
**Describe the bug**
I get validation errors (type_error's) when loading some of my *.mdu files.

I think some _changes_ are needed in:  hydrolib.core.io.mdu.models.py

[physics]
umodLin ; _type should be float instead of int_ to avoid the validation error # Note that based on the D-Flow FM manual, you might expect an integer. However, in D-Flow FM this is read as a float. Change needed in HYDROLIB-core or in D-Flow FM?
betaSpiral ; _type should be float instead of int_

[trachytopes]
TrtL ; _type should be [str] instead of [int]_
TrtDef ; _type should be [str] instead of [int]_

[wind]
relativewind ; _type should be float instead of bool_   # this recently changed in D-Flow FM from boolean to float

**Comment by priscavdsluis** [comment]
Hi @arthurvd, as discussed, could you update the manual for the 5 keywords?
