### ISSUE TITLE
Update "First steps" tutorial to notebook

### ISSUE THREAD

**Issue by rhutten** [Deltares/HYDROLIB-core#246]
**What is the need for this task.**
The HYDROLIB team strives to create notebooks as tutorial that can be launched in binder

**What is the task?**

- improve first steps tutorial: some steps are missing such as the creation of branch, calculation grid and adding of a profile.
- create notebook
- include binder option to documentation

**Additional context**

**Comment by arthurvd** [comment]
Notebook ok now. The binder link must be generated automatically and only for the html version of this notebook.
Will close this issue and continue that work under new issue #285.
