### ISSUE TITLE
Writing FrictionModel gives ValidationError

### ISSUE THREAD

**Issue by Robbertdelange** [Deltares/HYDROLIB-core#251]
**Describe the bug**
When reading a frictionfile and immediately writing it into a FrictionModel Pydantic gives a validationerror: 
_*** pydantic.error_wrappers.ValidationError: 1 validation error for FrictionModel
definition
  extra fields not permitted (type=value_error.extra)_

**To Reproduce**

1. Read FMmodel:
```
input_mdu = Path(r"C:\Hydrolib\Dhydro_changefrict\data\Zwolle-Minimodel\1D2D-DIMR\dflowfm\flowFM.mdu")
fm = FMModel(input_mdu)
```
2. Read frictionfiles:
`dfchan = pd.DataFrame([f.__dict__ for f in fm.geometry.frictfile[0].branch])`
3. Now the "Channels" frictionfile is loaded, for example.
5. Immediately write dataframe to FrictionModel:
`_frictmodel = FrictionModel(definition=dfchan )_`
6. Code gives error, but doesn't give which extra field is not permitted, or it is the 'definition' field, which I do not define.

**Expected behavior**
Write a new FrictionModel to be able to ".save" the model later. 

**Screenshots**
![image](https://user-images.githubusercontent.com/92364567/174036962-a0f1f451-21b3-49ab-9be3-d98d74f1050d.png)

**Version info (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 0.1.5]

**Additional context**
The keys in de dfchan are:
['comments', 'branchid', 'frictiontype', 'functiontype', 'timeseriesid',
       'numlevels', 'levels', 'numlocations', 'chainage', 'frictionvalues',
       'datablock', '_header']
I guess all are okay to use as input for the FrictionModel, but possibly I am wrong.

**Comment by arthurvd** [comment]
Hi @Robbertdelange : I think you have use the `CrossDefModel` as an inspiration for creating this `FrictionModel`.
The error is indeed somewhat technical, but it does point you to the cause: FrictionModel does not have a field `definition`. Instead, I guess you want to assign the dataframe contents to the `FrictionModel.branch` list, see APIdocs on:
https://deltares.github.io/HYDROLIB-core/0.2.1/reference/friction/#hydrolib.core.io.friction.models.FrictionModel

Once you have that changed, also pay attention to the `frictmodel = FrictionModel(definition=dfchan )`, I don't think directly passing the dataframe will work. Instead you may want to try something like `frictmodel = FrictionModel(branch=dfchan.to_dict('records'))`.

**Comment by Robbertdelange** [comment]
Thanks @arthurvd. I now understand how to append dataframes to the Model functions and what the error was about. Thanks for the explanation, it now works fine for me.

**Comment by arthurvd** [comment]
@Robbertdelange: do you still have that working code fragment, to document the solution to your question here?

**Comment by Robbertdelange** [comment]
Thanks for the reminder. The working code fragment is as follows:
`dfchan = pd.DataFrame([f.__dict__ for f in fm.geometry.frictfile[0].branch])
frictmodel = FrictionModel(branch=dfchan.to_dict('records'))
`
