### ISSUE TITLE
Pytest give warnings due to missing files

### ISSUE THREAD

**Issue by rhutten** [Deltares/HYDROLIB-core#252]
**Describe the bug**
When executing the command: 'Poetry run pytest' several warnings pop-up. Few of these warnings are related to output, while others result from missing input. Please fix these warnings

**To Reproduce**
In dev containter:
1. Go to terminal
2. Type 'Poetry run pytest'
3. Check the warnings

**Expected behavior**
No warnings should occur when running pytests

**Screenshots**
![image](https://user-images.githubusercontent.com/55204099/174573768-70ab8551-8fd6-4922-a109-0a8b8d0cc27f.png)

**Comment by BeardedPlatypus** [comment]
This was actually more insidious than just some random warnings. When models with `pathsRelativeToParent` set to `false` were read, the read logic still interpreted it wrongly as `pathsRelativeToParent` `true`. This meant it couldn't find the models, and generated the warning. 

When the model was subsequently saved, the default model was written to the path found with `pathsRelativeToParent` set to `false`. So the test did not fail, as it could still correctly found a file written at the expected path.

As part of #82 this warning should be changed to an error, thus making this mistake more obvious.

The read logic has been adjusted to correctly determine the `pathsRelativeToParent` value.
