### ISSUE TITLE
Create toplevel hydrolib.core.io.dflowfm tree structure for FMModel input

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#258]
**What is the need for this task.**
Currently in hydrolib.core.io many subdirectories exist for FM related modules. 
One subdirectory in hydrolib.core.io is meant for RR modules. 
hydrolib.core.io has grown a bit messy because of this. 

**What is the task?**
Move all FM related subdirecties in hydrolib.core.io to hydrolib.core.io.dflowfm

**Additional context**
Changing the namespace for all FM objects might require a lot of rework in the documentation and code that is dependent on it. 

See #168 for RR

**Comment by priscavdsluis** [comment]
We should also consider updating and using the __init__.py files to make imports easier as advised by @BeardedPlatypus

**Comment by tim-vd-aardweg** [comment]
Eventhough all the work for this issue has been done, we decided to wait until the next release to actually merge it, because this issue will obviously cause all sorts of merge conflicts.

It may be quicker to start this issue from scratch after the release, than to fix all the merge conflicts.
