### ISSUE TITLE
Create 0.3.0 release

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#280]
**What is the task?**
Prepare and release the 0.3.0 release from main.
* release on GitHub
* release on PyPI
* documentation pushed for 0.3.0 release
* afterwards, document the release steps as "developer/maintainer" documentation

**Additional context**
Hopefully PRs #269 and #277 can still be included in this release. In collaboration with @evetion.

**Comment by priscavdsluis** [comment]
Together with @evetion, releases HydroLib-core on GitHub and PyPi:
-  https://github.com/Deltares/HYDROLIB-core/releases/tag/0.3.0
- https://pypi.org/project/hydrolib-core/0.3.0/

**Comment by arthurvd** [comment]
I tested the install OK:
```
(base) C:\Users\dam_ar>pip install  --use-deprecated=legacy-resolver hydrolib-core==
ERROR: Could not find a version that satisfies the requirement hydrolib-core== (from versions: 0.1.0, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 0.3.0)
# ^^^ ignore the error, this correctly shows that 0.3.0 is available

(base) C:\Users\dam_ar>pip install  --use-deprecated=legacy-resolver hydrolib-core>=0.3

(base) C:\Users\dam_ar>pip show hydrolib-core
Name: hydrolib-core
Version: 0.3.0
Summary: Python wrappers around D-HYDRO Suite.
Home-page: https://deltares.github.io/HYDROLIB-core
Author: Deltares
Author-email: None
License: MIT
Location: c:\users\dam_ar\anaconda3\lib\site-packages
Requires: numpy, lxml, netCDF4, meshkernel, pydantic
Required-by:
```
