### ISSUE TITLE
net writer should not produce NaNs as fill values

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#290]
**Describe the bug**
When creating  basic 2D mesh and saving it, unsupported NaN values are written for the mesh node z values.
(Discovered in a test by @Hofer-Julian)

**To Reproduce**
1. Execute this script:
```python
from hydrolib.core.io.net.models import NetworkModel

network = NetworkModel()
network.mesh2d_create_rectilinear_within_extent(extent=(-5, -5, 5, 5), dx=1, dy=1)
network.save()
``` 
2. The working dir should now contain a file `network.nc`
3. Inspect that file via a NetCDF viewer (panoply / hdfview / ..)
4. Observe NaNs in:
```
        double mesh2d_node_z(mesh2d_nNodes) ;
                mesh2d_node_z:_FillValue = NaN ;
                mesh2d_node_z:standard_name = "altitude" ;
// ...
        double mesh2d_face_z(mesh2d_nFaces) ;
                mesh2d_face_z:_FillValue = NaN ;
                mesh2d_face_z:units = "m" ;
                mesh2d_face_z:mesh = "mesh2d" ;

```

**Expected behavior**
Use numeric (non-NaN) _FillValue instead, for example the netcdf default value (available in `netCDF4.default_fillvals{'f8'}` for doubles for example.
Find an alternative for current code:
```python
        mesh2d_node_z = ncfile.createVariable(
            "mesh2d_node_z", np.float64, nc_mesh2d.node_dimension, fill_value=np.nan
        )
```

**Comment by tim-vd-aardweg** [comment]
A quick update on my findings so far:
If you set the `fill_value` in `createVariable()` (let's say we set it to `10`) and any of the values you assign to this variable are `10`, then python netCDF4 will write `NaN` to the file instead.
