### ISSUE TITLE
Spyder freeze upon print of ForcingModel

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#315]
**Describe the bug**
Freeze of Spyder IDE upon print of m.forcing. I discovered it while trying to figure out how to get the data out of this object, printing it (or the type) then helps to understand. In the example I used a large bc file. I expect small bc files do not result in this issue.

**To Reproduce**
```
from pathlib import Path
from hydrolib.core.io.bc.models import ForcingModel

file_bc = Path(r'p:\11208053-004-kpp2022-rmm1d2d\C_Work\09_Validatie2018_2020\dflowfm2d-rmm_vzm-j19_6-v2d\boundary_conditions\rmm_rivdis_meas_20171101_20210102_MET.bc')

m = ForcingModel(file_bc_wl)
print(m.forcing)
```

**Expected behavior**
No freeze upon print, maybe just print the type/instance? At least a fast __str__ instance would be nice to have in the ForcingModel class.

**Version info (please complete the following information):**
 - OS: Windows, Anaconda, Spyder
 - Version: 0.3.0

**Comment by veenstrajelmer** [comment]
If one prints a pandas dataframe or numpy array, parts are left out so there is a prettyprint which is not that intense on time/performance:
```
quantity                  dischargebnd
unit                              m3/s
Lek_0001                              
2017-11-01 00:00:00+01:00         5.38
2017-11-01 00:10:00+01:00         6.95
2017-11-01 00:20:00+01:00         4.37
2017-11-01 00:30:00+01:00         6.03
2017-11-01 00:40:00+01:00         6.88
                               ...
2021-01-01 23:20:00+01:00       445.83
2021-01-01 23:30:00+01:00       449.17
2021-01-01 23:40:00+01:00       451.27
2021-01-01 23:50:00+01:00       453.58
2021-01-02 00:00:00+01:00       456.47

[162034 rows x 1 columns]

I guess the non-pretty print is inherent to the use of nested lists in m.forcing[0].datablock. Maybe implenting a __str__ method where datablock is left out (or pretty printed) would be convenient.

**Comment by veenstrajelmer** [comment]
@priscavdsluis: This works quite well, and it is now also easier to view the relevant contents of the list of objects in m.forcing (like that all objects are a waterlevelbnd. However, it is of course a bit misleading that datablock is now printed as [] as if empty, but I can imagine that is for later. What I noticed is that my testfile now takes longer to run. So Spyder does not freeze, but there is apparently more overhead.

**Comment by priscavdsluis** [comment]
@veenstrajelmer, thanks for the feedback! I will investigate it further.

**Comment by priscavdsluis** [comment]
I have updated the implementation.
It should be clear now that the datablock is intentionally omitted.
I wonder if the performance has improved as well.

**Comment by veenstrajelmer** [comment]
Adding 'omitted' is a great idea. The performance of printing has also really improved. Thanks!
