### ISSUE TITLE
t3D header not correct yet

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#317]
**Describe the bug**
Some issues with t3D header:
Missing:
 - vertical position 1/2/3/n is not supported, should be added to QuantityUnitPair (or new object)
 - timeInterpolation not written to file for T3D blocks
 - verticalPositionType "ZDatum" but is not available in VerticalPositionType class
 - verticalPositionType "ZSurf" is missing (_newly added to this issue, Sep 29 '22_)
Inconsistencies:
 - "verticalPositions" is written, while "Vertical position specification" is expected (in 2D3D manual). Does both work?
   **Answer:** in kernel: yes, in GUI: no. And we should move to 1 consistent keyword. Decision (Oct 13, 2022): support only the latest kernel keywords  in the model fields + support spaced old keywords for compatibility via a pre root_validators, e.g., "Vertical position specification"
  (Pydantic already turns spaced fields into underscore fields, e.g., "vertical_position_specification")
  Background for D-HYDRO developers, see internal issue UNST-5801.
 - "verticalPositionType " is written, while "Vertical position type" is expected (in 2D3D manual). Does both work?
  **Answer:** same as previous one. Support "vertPositionType" and backwards compability for "Vertical position type".

In summary, these are the correct keywords:
* `timeInterpolation`
* `vertPositionType`
* `vertPositions`
* `vertInterpolation`
* `vertPositionIndex`

**To Reproduce**
```
from pathlib import Path
import numpy as np

from hydrolib.core.io.bc.models import (
    ForcingModel,
    QuantityUnitPair,
    TimeInterpolation,
    T3D,
    VerticalPositionType,
)

bc_south = ForcingModel()
depth_list = [-2000,-1000,-500,-100]
times_list = np.array([0,60,120,180,240,300,360,420])
datablock = np.random.uniform(low=-40, high=130.3, size=(len(times_list),len(depth_list)))
datablock_incltime = np.concatenate([times_list[:,np.newaxis],datablock],axis=1)
list_QUP_perlayer = [QuantityUnitPair(quantity='salinity', unit='1e-3') for iL in range(len(depth_list))] #TODO REPORT: verticalposition 1/2/3/n is not supported
ts_one = T3D(name='3d_bnd_0001',
             verticalpositions=depth_list, #TODO: should be "Vertical position specification = [..]" but is verticalPositions = [..]" (both possible?)
             verticalInterpolation='linear',
             verticalPositionType=VerticalPositionType('ZBed'), #TODO: should be "Vertical position type = zdatum" but is "verticalPositionType = ZBed" (zdatum is niet beschikbaar)
             quantityunitpair=[QuantityUnitPair(quantity="time", unit="seconds since 2022-01-01 00:00:00 +00:00")]+list_QUP_perlayer,
             timeinterpolation=TimeInterpolation.linear, #TODO: not passed on to bc file
             datablock=datablock_incltime.tolist(), 
             )
bc_south.forcing.append(ts_one)
bc_south.save(filepath=Path("steric_south2.bc"))
```

**Expected behavior**
described in description

**Version info (please complete the following information):**
 - OS: Windows, Anaconda, Spyder
 - Version: 0.3.0

**Comment by arthurvd** [comment]
@tim-vd-aardweg : I've update the original issue description at the top. 
Note the correct naming: "Vertical position specification", "vertical position", "Vertical position specification".

**Comment by tim-vd-aardweg** [comment]
@arthurvd Thanks for checking this. So we basically have to adhere to the 2D3D manual for the .bc file then? So we also have to change `timeInterpolation` (which is the current implementation in Hydrolib) to `Time Interpolation`

**Comment by arthurvd** [comment]
> @arthurvd Thanks for checking this. So we basically have to adhere to the 2D3D manual for the .bc file then? So we also have to change `timeInterpolation` (which is the current implementation in Hydrolib) to `Time Interpolation`?

No, let's keep that at the new "timeInterpolation" keyword already. I am preparing an issue where we make kernel+GUI consistent again with all new lowerCamelCase namings, and timeInterpolation is now already supported by both kernel and GUI.

**Comment by tim-vd-aardweg** [comment]
Ok!

**Comment by tim-vd-aardweg** [comment]
I will
