### ISSUE TITLE
Suggestion for easier access to xy values from PolyFile object

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#329]
**Is your feature request related to a problem? Please describe.**
When plotting a pli file, currently I need to extract x/y locations with a for loop. Is it also possible to access the x/y coordinates directly or can this be added?
```
from hydrolib.core.io.polyfile.parser import read_polyfile #TODO: should be replaced with PolyFile after bugfix
file_pli = Path(r'c:\DATA\dfm_tools_testdata\GSHHS_high_min1000km2.ldb')
polyfile_object = read_polyfile(file_pli,has_z_values=False)
pli_PolyObjects = polyfile_object['objects']

fig,ax = plt.subplots()
for iPO, pli_PolyObject_sel in enumerate(pli_PolyObjects):
    print(f'processing PolyObject {iPO+1} of {len(pli_PolyObjects)}: name={pli_PolyObject_sel.metadata.name}')
    xvals = np.array([p.x for p in pli_PolyObject_sel.points])
    yvals = np.array([p.y for p in pli_PolyObject_sel.points])
    ax.plot(xvals,yvals)
```

**Describe the solution you'd like**
Access all xy values without looping over all points. Shapely for instance has a .coords.xy function:
https://stackoverflow.com/questions/20474549/extract-points-coordinates-from-a-polygon-in-shapely

**Comment by veenstrajelmer** [comment]
This is also applicable for XYZModel and XYNmodel. Currently, I created these funtions, but it would be better if there would be some generic conversion tool: https://github.com/openearth/dfm_tools/blob/work_jelmer/dfm_tools/hydrolib_helpers.py

**Comment by priscavdsluis** [comment]
Closing this issue as discussed with @veenstrajelmer.
It would be nice if we can find something more generic that will work for multiple objects. 
Jelmer can do that now easily locally.

I think if more users ask for this kind of functionality we can take a look at it in a more broader way.
