### ISSUE TITLE
Keyword [output] writebalancefile generated in mdu after setting new crossdef file

### ISSUE THREAD

**Issue by jingdeng0314** [Deltares/HYDROLIB-core#331]
**Describe the bug**
I am using Hydrolib core to change crossdef file in mdu. The original mdu does not contain Keyword [output] writebalancefile. However, after setting the new crossdef file and save, the new mdu then contains Keyword [output] writebalancefile. This could cause errors when running the model using run.bat. If I delete the keyword manually in the mdu file, the model can be successfully run.

According to the user manual, the Keyword [output] writebalancefile should have been removed in the latest version. I am wondering why this happens, and how I can solve this problem especially if I want to do iterations then I cannot delete the keyword manually every time.

**To Reproduce**
Link to the models:
https://royalhaskoningdhv.box.com/s/5dimaqjge6pvhtes7o9700t7pumqw9hx

```
from pathlib import Path
from hydrolib.core.io.crosssection.models import CrossDefModel
from hydrolib.core.io.mdu.models import FMModel

# original mdu
p = Path(r'C:\Users\923128\Box\BH8407 TKI5 DH VC WIP\03_Info\00_Example_DHydro_model\20220829_SHARED\AOW_mortelbeek_xml_2022.04\dflowfm\Mortelbeek.mdu')
fm = FMModel(p)

# setting new crossdeffile
cross_def_new = CrossDefModel(Path(r'C:\Users\923128\Box\BH8407 TKI5 DH VC WIP\03_Info\00_Example_DHydro_model\20220829_SHARED\crossdef_1.ini'))
fm.geometry.crossdeffile = cross_def_new

# save new mdu
fm.output.outputdir = r'C:\Users\923128\Box\BH8407 TKI5 DH VC WIP\03_Info\00_Example_DHydro_model\20220829_SHARED'
fm.filepath = r'C:\Users\923128\Box\BH8407 TKI5 DH VC WIP\03_Info\00_Example_DHydro_model\20220829_SHARED\new.mdu'
fm.save(recurse=False)
```

**Version info:**
 - OS: Windows
 - Hydrolib core version 0.3.0

**Additional context**
If there is any questions or feedbacks about this problem, please contact me, @rinekeh or  @LisaWeijers . Thanks!

**Comment by arthurvd** [comment]
Hi @jingdeng0314, I just confirmed that this issue is solved using the latest sources from main (was fixed on July 26).
The upcoming 0.3.1 release will contain this bugfix and should become available within 2 weeks approximately.
