### ISSUE TITLE
add new object for branches.gui

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB-core#332]
**Is your feature request related to a problem? Please describe.**
For an urban model with pipes, a branches.gui file is needed for the GUI to import the model correctly. For now, this file is not implemented in hydrolib-core. 

**Describe the solution you'd like**
Implementation of a new branches.gui model 

**Describe alternatives you've considered**
Alternatively, we can implement this file in hydromt-delft3dfm. But this means other projects within the hydrolib cannot make use of it. 

**Additional context**

**Comment by xldeltares** [comment]
branch created : https://github.com/Deltares/HYDROLIB-core/tree/feature/332_branches_gui

**Comment by rhutten** [comment]
issue is already implemented and merged to main
