### ISSUE TITLE
branchOrder not written to nc file

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB-core#334]
**Describe the bug**
branchOrder not written to nc file. 

**To Reproduce**
in net\models.py on line 775: self.network1d_branch_order = np.append(self.network1d_branch_order, -1)
The branchOder is always appended with -1.

**Expected behavior**
branch_order is passed to the function as an input argument. It should be used here
in net\models.py on line 775: self.network1d_branch_order = np.append(self.network1d_branch_order, branch_order)

**Comment by rhutten** [comment]
Issues is already merged to main
