### ISSUE TITLE
ExtModel cannot handle path formats from different OS

### ISSUE THREAD

**Issue by SCLaan** [Deltares/HYDROLIB-core#339]
**Is your feature request related to a problem? Please describe.**
When working on Windows **ExtModel** (and maybe other functions) cannot read Unix paths (and probably vice-versa). With many quick pre- and post-processing steps on Windows machines and the larger simulations on a Linux cluster an automatic conversion of path formats when reading data will be necessary. Also for saving it will be a good feature to be able to choose the output format (Windows/Unix).

**To Reproduce**
1. Make an external forcings file (dummy.ext) with the content:
```
[boundary]
quantity=waterlevelbnd
locationfile=/p/11203669-004-kpp-morfwad-krw-slib/Waddenzee_model_hydro/04_Boundary_conditions/east_v05_part2.pli
forcingfile=/p/11203669-004-kpp-morfwad-krw-slib/Waddenzee_model_hydro/04_Boundary_conditions/east_part2_wl_20151222_20180101.bc
return_time=0.0000000e+000
```
2. Open external forcings file in python on Windows:
```
from pathlib import Path
from hydrolib.core.io.ext.models import ExtModel
extFile = Path(r'dummy.ext')
extData = ExtModel(extFile)
```
3. This causes an error like:
```
DWSM-FM_bc.ext -> boundary -> 19 -> forcingFile
  File: `\\directory.intra\Project\p\11203669-004-kpp-morfwad-krw-slib\Waddenzee_model_hydro\04_Boundary_conditions\south_temp_20151222_20180101.bc` not found, skipped parsing. (type=value_error)
```

**Describe the solution you'd like**
- ExtModel to automatically determine the format of paths and to be be able to read the data regardless of the used OS.
- ExtModel to include an option for saving in a different format (e.g. save as Unix on Windows). Ideally this is set based on the format already used.

**Technical design**
(Proposal by @arthurvd)
* Implementation in the `FileModel` class is probably enough and as high as possible.
* It should support optional configuration of the path-style (Windows or Unix-like) during model `load()`
* A similar optional argument should support a custom path-style upon `save()` of a model
* By default, the current OS style must be detected and used.
* Path style options can become a small Enum class.
* Probably this must become a data attribute in the `FileModel` class, such that it can also be set while creating models from scratch, e.g.:
```python
fmmodel = FMModel()
extmodel = ExtModel()
extmodel.filepath = '/p/foo/forcing.ext`
extmodel.path_style = PathStyle.UNIXLIKE   # or do we even autodetect this in set_attribute or so?
```
* For absolute paths, no translation is possible (we don't know which Windows driveletter corresponds with which leading root dir on Linux). OR: should the user be able to supply some mapping table of absolute path parts?
* Final remark: before making all of this: INVESTIGATE whether `pathlib` or some other package already has some built-in features for this.

**Comment by veenstrajelmer** [comment]
Suggestion: always write forward slashes (windows also supports this), then the only issue that remains are the hardcoded drive letters

**Comment by priscavdsluis** [comment]
I put this is back in TODO for now, since I would like to discuss this with the rest of the team:

- Resolving absolute paths from posix to windows will indeed be a challenge. For example, in this, case `/p` has to be converted to `p:`. This in itself is not difficult, but it will become trial and error code: if the converted path can be found, it was apparently an absolute path, otherwise it must be a relative path. From windows to posix, will be easier. 
-  I agree with @veenstrajelmer, that we could always write forward slashes. This way, all relative paths that were written with hydrolib-core can be correctly read with hydrolib-core on any OS. However, what about models that already exist with backward slashes?

**Comment by priscavdsluis** [comment]
Hi @SCLaan,

The following points were your deisred solutions:
> ExtModel to automatically determine the format of paths and to be be able to read the data regardless of the used OS.
> ExtModel to include an option for saving in a different format (e.g. save as Unix on Windows). Ideally this is set based on the format already used.

**For the first point**, I have not implemented an auto-detect of the path formats. This might require a more complex solution to achieve. I think it will be easier and cleaner to use a parameter (as @arthurvd suggested) when loading a model from a file. The current implementation offers the following solution:
```
model = ExtModel(filepath, path_style=PathStyle.UNIXLIKE)
```

This will read the model with the assumption that all file references are written with the unix format.

**For the second point**, do you want:

- The user to be able to manually set the format option
- The format to be automatically set to the original format of the file (so no user involvement)
- Both: user is able to set option manually, but when not provided by the user the original format will be used.

**Comment by priscavdsluis** [comment]
For now I have implemented the following

## User is able to load a model on Windows with Unix file paths, and vice versa
Usage example on Windows when loading a model with Unix file paths:
`model = FMModel(filepath=Path("p:/model/FlowFM.mdu"), path_style=PathStyle.UNIXLIKE)`

Conversion example from file to in memory:
**/p/model/FlowFM_net.nc** -> **p:/model/FlowFM_net.nc**
**model/FlowFM_net.nc** -> **model/FlowFM_net.nc**

Usage example on Linux/MacOS when loading a model with Windows file paths:
`model = FMModel(filepath=Path("/p/model/FlowFM.mdu"), path_style=PathStyle.UNIXLIKE)`

Conversion example from file to in memory:
**p:/model/FlowFM_net.nc** -> **/p/model/FlowFM_net.nc**
**p:\model\FlowFM_net.nc** -> **/p/model/FlowFM_net.nc**
**model/FlowFM_net.nc** -> **model/FlowFM_net.nc**

Note that the file path that is passed to the initializer of the model needs to be in the file path format of the OS hydrolib-core is running on.

## User is able to save a model on Windows with Unix file paths, and vice versa

**Comment by SCLaan** [comment]
Hi @priscavdsluis,
Thank you! I have tested the new code and it works fine for me. I was able to read in models with Unix filepaths on Windows and save the model output again in both Unix and Windows format. This is passed on from the mdu to the (new) ext file. I see no problem in asking users to set the file format themselves.

**Comment by priscavdsluis** [comment]
@SCLaan, thanks for your feedback! Good to hear it works.

**Comment by arthurvd** [comment]
@SCLaan : wil jij deze nieuwe functionaliteit testen?
Het staat in @priscavdsluis's branch #361 ([feat/339-handle-path-format-different-OS](https://github.com/Deltares/HYDROLIB-core/tree/feat/339-handle-path-format-different-OS)), en je gebruikt het bijvoorbeeld zo (op Windows verwijzend naar files met Linux `/p/enzovoort` paden.
```python
inputmdu=Path(r"p:/model/flowfm.mdu")
fmmodel = FMModel(filepath=inputmdu, path_style="unix")

# [..]
outputmdu=Path(r"p:/model/flowfm_modified.mdu")
fmmodel.filepath = outputmdu
fmmodel.save(path_style="unix")
```

**Comment by priscavdsluis** [comment]
#474 can be merged once this issue is merged (should make tests green for that issue)

**Comment by SCLaan** [comment]
> @SCLaan : wil jij deze nieuwe functionaliteit testen? Het staat in @priscavdsluis's branch #361 ([feat/339-handle-path-format-different-OS](https://github.com/Deltares/HYDROLIB-core/tree/feat/339-handle-path-format-different-OS)), en je gebruikt het bijvoorbeeld zo (op Windows verwijzend naar files met Linux `/p/enzovoort` paden.
> 
> ```python
> inputmdu=Path(r"p:/model/flowfm.mdu")
> fmmodel = FMModel(filepath=inputmdu, path_style="unix")
> 
> # [..]
> outputmdu=Path(r"p:/model/flowfm_modified.mdu")
> fmmodel.filepath = outputmdu
> fmmodel.save(path_style="unix")
> ```

I did some quick tests and this seems to be working fine. I think this issue can now be closed.
