### ISSUE TITLE
Do not read all connected model files

### ISSUE THREAD

**Issue by SCLaan** [Deltares/HYDROLIB-core#340]
**Is your feature request related to a problem? Please describe.**
At least ExtModel reads all connected input files. Some bc-files can be very large, which can take a lot of time or even cause a memory overload.

**Describe the solution you'd like**
There should be an option to just read the header or name/path of connected files without reading all the contents. Then only files that will be edited can be read entirely.

**Describe alternatives you've considered**
Remove some lines linking to heavy files from the mdu/ext to be able to work with the rest of the model input.

**Comment by priscavdsluis** [comment]
Closing issue as it is a duplicate of #355.

**Comment by priscavdsluis** [comment]
Duplicate of #355
