### ISSUE TITLE
Investigate possibility of installing hydrolib-core in sub packages.

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#346]
**Is your feature request related to a problem? Please describe.**
Hydrolib-core is extended with more and more functionality. For the user, it would be nice if they can choose which functionality to install. 

**Describe the solution you'd like**
User should be able to pip install hydrolib-core.geomtry or hydrolib-core.io.rtc for example.

**Comment by arthurvd** [comment]
Will close this issue as "Won't Do" for now, because hydrolib-core is small enough to stay a single package.
It's more important to be able to install hydrolib (non-core) packages as separate packages, see issue https://github.com/Deltares/HYDROLIB/issues/151
