### ISSUE TITLE
Support Tim files

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#348]
**Is your feature request related to a problem? Please describe.**
Even though the new format is .bc files, many models still contain .tim files. 

**Describe the solution you'd like**
Support tim files as time series files.
* See format description in https://content.oss.deltares.nl/delft3d/D-Flow_FM_User_Manual_1D2D.pdf#section.C.4
* Support comment lines (starting with Either * or #), and store them as strings, such that they are preserved when saving a .tim file again.
* Do NOT further parse/interpret comment lines in more detail (e.g., we'll not try to derive a reference date/time from any comment line)
* Do NOT support comments at the end of regular data lines
* While printing/saving a tim file: make sure the column values are aligned, by the use of fixed width number formats and fixed whitespace.
* Both the whitespace and the number format would be nice if it is configurable by the user through a `SerializerConfig` (see how this was done for #308)

**Comment by MRVermeulenDeltares** [comment]
example of .tim file:

`  0.000000    0.0000000
 10.000000    0.0100000
 20.000000    0.0000000
 30.000000   -0.0100000
 40.000000    0.0000000
 50.000000    0.0100000
 60.000000    0.0000000
 70.000000   -0.0100000
 80.000000    0.0000000
 90.000000    0.0100000
100.000000    0.0000000
110.000000   -0.0100000
120.000000    0.0000000`

**Comment by MRVermeulenDeltares** [comment]
Volgende besproken met @veenstrajelmer:

Vraag voor Jelmer : Is iedere tijd uniek of kan een tijd meerdere keren voorkomen?
- mag niet meerdere keren voorkomen
- nalopen hoe dit bij bc files wordt gedaan
- error bij meerdere keren dezelfde tijd

niet numerieke waardes mogen niet voorkomen buiten comments om
- nalopen hoe dit bij bc files wordt gedaan
- consistency nalopen

vraag voor Jelmer: Wil je dat de gebruiker het schrijven van de timfile op dezelfde manier kan configureren als bij bv. het data block van de bcfile?
e.g. whitespaces tussen data, comma delimited, etc..
- fijn als de colommen onder elkaar staan, dat het uitgelijnt staat
- niet al te veel moeite in stoppen

zowel lezen als schrijven is handig
- terugleveren van data in lijn met bestaande onderdelen en efficient in te lezen

vraag voor Jelmer: moeten comments ook ingelezen worden? --> als een file wordt ingelezen, moet er bij schrijven dan precies hetzelfde uitkomen?
-de comments moeten ingelezen worden en ook worden terug gezet als er wordt geschreven

**Comment by MRVermeulenDeltares** [comment]
questions Support Tim files

- how would you like to receive data if you use a timmodel?
 a dict or a list and how would you like these to be setup? and how should comments be used in this?
Tim file: uit gaan van een data blok met alleen een comment bovenin.
Bespreken met arthur als er full line comments tussen de data staat.

- how should a full line comment be handled when it is inbetween data? should it be ignored, should it be saved, should an error be thrown?
Ask arthur --> error or ignored? Not saved.
throw an error --> verify with Arthur

- how should a non numeric number behind a data line  be handled?
should the line be skipped, should an error be thrown?

throw an error --> verify with Arthur
