### ISSUE TITLE
No validation for quantity in ForcingModel

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#357]
**Describe the bug**
As I was wondering whether it would be possible to force timeseries for structure model via bc files, I thought I'd give it a go expecting errors. However, I can freely think of a quantity and it is written without validation. Would it not be convenient if these were also validated?

**To Reproduce**
```
from hydrolib.core.io.bc.models import (
    ForcingModel,
    QuantityUnitPair,
    TimeSeries,
)
from hydrolib.core.io.ext.models import (
    ExtModel,
    Boundary
)
import numpy as np
from pathlib import Path

ext_bnd = ExtModel()
ForcingModel_object = ForcingModel()

quantity = 'structurebndtesting'

datablock_incltime = np.concatenate([np.array([0,10,20,30])[:,np.newaxis],np.array([0,360,360,0])[:,np.newaxis]],axis=1)

ts_one = TimeSeries(name='hvsl1',
                    quantityunitpair=[QuantityUnitPair(quantity="time", unit='minutes since 2012-01-01 00:00:00'),
                                      QuantityUnitPair(quantity=quantity, unit='m')],
                    timeinterpolation='linear',
                    datablock=datablock_incltime.tolist(), 
                    )

ForcingModel_object.forcing.append(ts_one)
#ForcingModel_object.save('a.bc')

boundary_object = Boundary(quantity=quantity,
                           locationfile=Path('a'),
                           forcingfile=ForcingModel_object,
                           )
ext_bnd.boundary.append(boundary_object)
```

**Expected behavior**
An error, since a 'structurebndtesting' is not a valid forcing I presume

**Version info (please complete the following information):**
 - OS: Windows 10, Spyder
 - Version: hydrolib-core, branch fix/317_t3d_header_not_correct

**Comment by arthurvd** [comment]
I understand your request, but I'm doubting whether this should be in `hydrolib-core`. As long as we're not maintaining a centralized list of valid quantity names, this will only lead to inconsistencies between FM kernel, FM plugin, FM manual and hydrolib-core.
I think we shouldn't do this now.

**Comment by veenstrajelmer** [comment]
OK, valid point, thanks!
