### ISSUE TITLE
support for str instead of Path

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/HYDROLIB-core#365]
**Is your feature request related to a problem? Please describe.**
Currently, it is necessary to import Path whenever using hydrolib functions: ``from pathlib import Path``

**Describe the solution you'd like**
This is acceptable, but I can imagine it would be fairly easy to add support for plain strings also, by converting all strings to Path(str) in hydrolib. This saves a bit of a hassle. At least, if chosen not to add support, I would suggest to raise a more explanatory error than this:
``AttributeError: 'str' object has no attribute 'is_absolute'``

Instead, explicitly informing the user to wrap ``Path()`` around the provided string.

**Comment by MRVermeulenDeltares** [comment]
in the FileModel class, the filepath variable can have a check on the input for path.
in the FileModel class, the save method can have a check on the input for path.
in the FileModel class, the constructor can have a check on the input for path.
Classes inheriting from the FileModel will have the path input resolved via the parent class.
e.g. the DIMR class inherits from the ParsableFileModel which in turn inherits from FileModel.
