### ISSUE TITLE
Merge hydrolib.core.io.net.models.Network in the pydantic hydrolib.core.models.Network

### ISSUE THREAD

**Issue by grongen** [Deltares/HYDROLIB-core#37]
Follow up of #31. The "Network" class "hydrolib.core.io.net.models.Network" should be merged into the "hydrolib.core.models.Network" class that inherits from BaseModel. This still gives some problems due to Pydantic combined with MeshKernel.

**Comment by evetion** [comment]
This was a pain to fix. The `NetworkModel`, based on pydantic now has a network attribute that refers to the non-pydantic `Network` class. In a sense we thus didn't integrate it, but I'm fine with that for now.
