### ISSUE TITLE
Make use of the new pydantic functionality of ~1.10

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#374]
**What is the need for this task.**
When developing certain features, the "discriminated union" was not yet supported in pydantic. So we had to make hacky validations for some objects; see for instance `ForcingBase.validate`.

At the moment, this functionality is merged back to pydantic (https://github.com/samuelcolvin/pydantic/pull/2336) and can be used.

**What is the task?**
- Search for `pydantic/pull/2336` in the code base
- Migrate the current implementation to the new implementation
-- For example the function property in ForcingBase and the type property in Structure.

The fixes in there apply to our:
- root validators not being triggered
- use of Union initialization
- use of Enum.value
And may not needed anymore, so they should be cleaned.

If required, make new issues for the above points.

**Comment by MRVermeulenDeltares** [comment]
Discussed with @priscavdsluis, the following validate in dimr\models.py will not be removed:

` 
   @classmethod
    def validate(cls, v):
        """Remove control element prefixes from parsed data."""
        if isinstance(v, dict) and len(v.keys()) == 1:
            key = list(v.keys())[0]
            v = v[key]
        return super().validate(v)
`

**Comment by MRVermeulenDeltares** [comment]
When closing this issue, issue #293 can be closed as duplicate.

**Comment by priscavdsluis** [comment]
Reverted the changes in commit:
`fc9fea0 - Revert "refactor: Make sure of the new Pydantic 1.10 functionality"` (11 april 23)

Reason:
Although the Union types generally work well for a happy flow with correct data, for an unhappy flow the messages to the user become super unclear.
This is because in the original implementation the type (e.g. a structure sub type) was initialized manually and later data is used to initialize and validate the object. This results in clear errors.
But if this is no longer done manually, pydantic attempts to initialize the correct type, but this only works reliably when the data is correct. If something in the data is wrong, no correct type can be initialized. This leads to very unclear messages (see for example the error in issue #497)
