### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by LisaWeijers** [Deltares/HYDROLIB-core#378]
**Describe the bug**
From the main docs page, if you click "Tutorials" under quickstarts for first time users it leads to the page tutorials/steps.md which gives a 404 error 

**To Reproduce**
1. Go to https://deltares.github.io/HYDROLIB-core/0.3.0/
2. Click on "Tutorials"
3. Leads to page https://deltares.github.io/HYDROLIB-core/0.3.0/tutorials/steps.md which gives 404 file not found error

**Comment by LisaWeijers** [comment]
steps.md does not exist in the tutorials folder anymore (think it existed in 0.2.0). Maybe this should be changed to tutorials.md?

**Comment by arthurvd** [comment]
Thanks Lisa, we discovered this last week already in the sources and fixed it there. Only the 0.3.0 docs were not regenerated.
For now you can use https://deltares.github.io/HYDROLIB-core/develop/
and in the upcoming 0.3.1 this will be correct again.
