### ISSUE TITLE
Adjust init files to make imports easier for users.

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#410]
**Is your feature request related to a problem? Please describe.**
Since we have moved all the dflowfm related object to the dflowfm package, many users have to upgrade their imports.
These imports will also be longer than they previsouly were.

**Describe the solution you'd like**
Make imports easier again by updating the init files, for dflowfm, rr and dimr.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered (if applicable).

**Additional context**
See #258 for the issue that restructured the dflowfm modules. 
Version: 0.3.1

**Comment by arthurvd** [comment]
Some first thoughts for discussion.

Possible imports that I can see being handy:
```
from hydrolib.core.dflowfm import *  # <== Everything public under hydrolib.core.io.dflowfm
from hydrolib.core.dimr import *     # <== Same for RR
from hydrolib.core.rr import *       # <== Same for RR
import hydrolib.core as hc           # <== Everything public: io/**/*, and in the future hydrolib.core.modeldata and hydrolib.core.geometry?

bcfile = hc.Boundary()     # Here I am in doubt: nothing shows that this is a dflowfm.ext.models.ForcingModel.models.boundary
                           # What if later we add hydrolib.core.io.hecras.***.Boundary?

# Deeper levels:
from hydrolib.core.io.dflowfm.structure import Weir  # <== Only shortcut to hydrolib.core.io.dflowfm.structure.models.*
```

**Comment by tim-vd-aardweg** [comment]
During a duscussion with @veenstrajelmer he mentioned his preferences (from most preferred to least preferred):
1) `import hydrolib.core as hc`
However, this may cause problems later on as we are polluting our namespace and may result in conflicts.

2) `import hydrolib.core.dflowfm as hcdfm`
This will require us to remove the `io` namespace, or add a hacky solution, for example by creating a dflowfm directory in the hydrolib.core directory that handles all the imports. This will require a discussion with @arthurvd about whether or not we can/should remove the `io` directory.

3) `import hydrolib.core.io.dflowfm as hcdfm`
This is easy to implement. I have been looking at how the `pandas` package handles this. They simple have a root level `__init__.py` where they import classes and methods from different subfolders. So we could do something like this in the `__init__.py` in our `dflowfm` folder:

```
from .common.models import (
    LocationType,
)

from .onedfield.models import (
    OneDFieldGeneral,
    OneDFieldGlobal,
    OneDFieldBranch,
    OneDFieldModel,
)

from .ext.models import (
    Boundary,
    Lateral,
    ExtGeneral,
    ExtModel,
)
```

The users would then be able to do the following:
```
import hydrolibcore.io.dflowfm as hcdfm

hcdfm.OneDFieldModel()
hcdfm.ExtModel()
```
