### ISSUE TITLE
Update the hydrolib.core namespace to just hydrolib-core 

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#421]
**Is your feature request related to a problem? Please describe.**
The namespace `hydrolib.core` was created with the idea in mind that more packages would be placed under `hydrolib` (next to `core`). The pip package we deliver is also called `hydrolib-core`. Since no other packages will be added to `hydrolib-core`, it makes sense to update `hydrolib.core` to `hydrolib-core`

**Describe the solution you'd like**

1. Rename the `hydrolib` folder to `hydrolib-core`.
2. Move all content from the `core` folder into `hydrolib-core` folder.
3. Remove the `core` folder.
4. Update all imports and references from `hydrolib.core` to `hydrolib-core`.  

**Additional context**
Version: 0.3.1

**Comment by tim-vd-aardweg** [comment]
We will not be going through with this change. We will keep `hydrolib.core`.
