### ISSUE TITLE
Some Models do not have a ._ext() attribute

### ISSUE THREAD

**Issue by hboisgon** [Deltares/HYDROLIB-core#434]
**Describe the bug**
When wanting to initialise some files and write them, the ._ext() attribute is not available for all, so far ._filename() seems to be.
This was found for CrossLocModel, StorageNodeModel.

**To Reproduce**
CrossLocModel._ext()

**Version info (please complete the following information):**
 - OS: [e.g. Windows]
 - Version 0.3.1+ (dev)

**Comment by arthurvd** [comment]
@hboisgon : can you explain in some more detail what is not working for you?
Classes `CrossLocModel`, `StorageNodeModel` (and many more) are subclasses of `IniModel`, which *has* method `_ext()` defined (it will return ".ini").

For example:
```python
from hydrolib.core.dflowfm import *

print(CrossLocModel._ext())
print(StorageNodeModel._ext())
```
Should produce:
```
.ini
.ini
```

**Comment by arthurvd** [comment]
Hi @hboisgon, I cannot reproduce this. With 0.4.1 I'm getting this:
```python
from hydrolib.core.dflowfm import CrossLocModel
CrossLocModel._ext()
# Out[53]: '.ini'
```
Let us know if this still an issue for you.
