### ISSUE TITLE
Implement meteo for external forcing

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB-core#446]
**Is your feature request related to a problem? Please describe.**
In project Santa Cruz, we need to implement rainfall on 2D grid as meteo forcing. For now hydrolib-core does not have the meteo implemented. 

**Describe the solution you'd like**
a new class Meteo(INIBasedModel) that writes a `[Meteo]` block for use inside an external forcings file.

**Comment by xldeltares** [comment]
@arthurvd: That would be great if you still could review/finish it in this sprint! I will create a PR and please feel free to work on it. Thanks!

**Comment by arthurvd** [comment]
@priscavdsluis / @tim-vd-aardweg / @MRVermeulenDeltares : our discussion about the diskOnlyFileModel will be continued under a new issue: #478.

**Comment by priscavdsluis** [comment]
I reviewed the PR and the changes look good. 
However there is the property `forcing` on the new Meteo object. I want to verify first if it is correct and find an example with non-global meteo data.
