### ISSUE TITLE
grid refinement based on samples

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB-core#447]
**Is your feature request related to a problem? Please describe.**
For now hydrolib-core only supports refine 2D grid based on polygon (function ```refine```. However, in many use cases, refine 2D grid based on samples (a raster file) is much more useful. 

**Describe the solution you'd like**
Support also refine based on samples. dhydamo and hydrolib-core do not have this option yet, but it is possible in meshkernelpy using function  ```mesh2d_refine_based_on_samples```.
Work will also include implementation in hydrolib and hydrolib-core.

**Describe alternatives you've considered**
Not Applicable.

**Comment by veenstrajelmer** [comment]
Since meshkernelpy is a dependency of hydrolib-core, why not use the meshkernelpy functionality directly?

**Comment by xldeltares** [comment]
After a discussion with @veenstrajelmer, we agreed that this part of the function can be implemented outside of hydrolib-core using meshkernel functions. therefore, closing this issue.
