### ISSUE TITLE
Create release 0.4.3 with MeshKernel update

### ISSUE THREAD

**Issue by priscavdsluis** [Deltares/HYDROLIB-core#452]

**Comment by veenstrajelmer** [comment]
Could the minimal required meshkernel version also be updated or does that not matter for hydrolib-core?
https://github.com/Deltares/HYDROLIB-core/blob/main/pyproject.toml#L24

**Comment by priscavdsluis** [comment]
@veenstrajelmer Unfortunately, when we increase the minimal required meshkernel version the API is not compatible anymore (>v2.0.0) because it contains breaking changes. Also from this version on the Linux/MacOS support is not included anymore.

I wish we could update but we have to wait unfortunately until macos support is available again (for the users of dfm_tools)

**Comment by priscavdsluis** [comment]
As discussed with the team, for now we will continue with making a release that does not support macOS users. 
Removing flag.
