### ISSUE TITLE
Add support for 'old' obs.xyn files (observationpoints)

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#459]
**Is your feature request related to a problem? Please describe.**
Currently, obs (and also crs) files are not supported by hydrolib. Upon reading them, the resulting dataset is empty. As a 2D modeller, I was not aware that this filetype is considered old, since it is being widely used in our models and therefore not possible to deprecate yet. Furthermore, I was not aware there existed a new alternative for it.

**Describe the solution you'd like**
Add support for *_obs.xyn (*_crs.pli files is handled under separate issue #364)

**Comment by tim-vd-aardweg** [comment]
Check if it can be subclassed from the xyz model.

**Comment by tim-vd-aardweg** [comment]
https://content.oss.deltares.nl/delft3dfm1d2d/D-Flow_FM_User_Manual_1D2D.pdf Section F.2.2.2 describes the .xyn format.

**Comment by veenstrajelmer** [comment]
Additional request: validate that there are no duplicate observation point names

**Comment by arthurvd** [comment]
> ```
> 1.23  3.45  'some text with spaces' And everything beyond does not matter
> 1.23 3.45 Only_the_first_word and the test is ignored
> ```
> 
> Would be great if both of the above cases result in an error instead.
> 
> Additional request: validate that there are no duplicate observation point names

@tim-vd-aardweg : if you're also ok with extending the scope of this issue a bit, let's keep Jelmer's two requests separate (and add @priscavdsluis's request too):
1. the first one under this same issue: raise an error from the parser if there is any text remaining on a line after successfully parsing the x+y+name already.
2. the validation of station name uniqueness now has an issue of its own: #483.
3. Finally, @priscavdsluis correctly remarked that api ref .md files must be added for the newly added `xyn` package scope. OK to that under this same issue.

**Comment by veenstrajelmer** [comment]
Thanks for the implementation. There are still some issues that I encounter
```
import hydrolib.core.dflowfm as hcdfm
from pathlib import Path
file_xyn = r'p:\archivedprojects\11206813-006-kpp2021_rmm-2d\C_Work\31_RMM_FMmodel\geometry_j19_6-v2\output_locations\rmm_vzm-j19_6-v2b_3_measurement_obs.xyn'
```

XYNModel exists, but is not exposed via init file, therefore the second line fails:
```
hcdfm.xyn.models.XYNModel(Path(file_xyn))
hcdfm.XYNModel(Path(file_xyn))
```

This stil returns an empty object without a warning or error. I would expect an error since the provided file cannot be read:
```
hcdfm.ObservationPointModel(Path(file_xyn))
```

Furthermore, as a user it might be easier to call the same object in case of a new or old obsfile, but I understand this would be more difficult to implement (so let's briefly discuss this). Also, I wonder if/how this is parsed when loading an FMModel, how does hydrolib-core distinguish between old/new obs files?

**Comment by veenstrajelmer** [comment]
Does not crash yet on invalid input: https://github.com/Deltares/HYDROLIB-core/issues/459#issuecomment-1484598572
Also, XYNModel.save('filename') raises `"TypeError: serialize() takes 3 positional arguments but 4 were given"`

**Comment by tim-vd-aardweg** [comment]
The error `"TypeError: serialize() takes 3 positional arguments but 4 were given"` is most likely given because the serializers now also include `ModelSaveSettings`. I will fix this tomorrow.

**Comment by tim-vd-aardweg** [comment]
There are two different ways names for the stations can be set:
1) By loading a `.xyn`
2) By setting the name in-memory (`point.n = "<station name>"`)

When loading the `.xyn` (1) the rules are simple. There are two possible ways for the user to specify the name:
i) Without single quotes:"
-- The name should be one word (=no spaces allowed).
-- If additional content is found after the name, we should raise an error.
ii) With single quotes:
-- The name may be multiple words (=may contain spaces).
-- If additional content is found after the closing single quote, we should raise an error.

When setting the name in-memory (2), the rules are as follows:
- The name may be a single word or multiple words (may contain spaces).
- When the name contains spaces it may enclosed by single quotes, but does not have to be. So both `point.n = "name with spaces"` and `point.n = "'name with spaces'" are fine`. Using double quotes is also fine: `point.n = '"name with spaces"'`.
- If the name has leading or trailing white spaces, they should be trimmed. (This is preferred by @veenstrajelmer over keeping the spaces and writing the name with single quotes to the `.xyn` file to keep the whitespaces). (e.g. `point.n = "    name with whitespace    "` should be stored in-memory as `namewithwhitespace` (and not as `    name with whitespace    `). It should be written to the `.xyn` file as `1.1 2.2 namewithwhitespace` (and not as `1.1 2.2 '    name with whitespace    '`.
-
