### ISSUE TITLE
Polyfile parser does not parse 2D boundary type of pli file correctly. 

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB-core#467]
**Describe the bug**
Polyfile parser does not parse 2D boundary type of pli file correctly. 
See example file: [Boundary01.pli.txt](https://github.com/Deltares/HYDROLIB-core/files/10968795/Boundary01.pli.txt)

**To Reproduce**
```
from pathlib import Path
from hydrolib.core.dflowfm.polyfile.parser import read_polyfile
fn = Path(r'Boundary01.pli')
read_polyfile(filename)
{'has_z_values': False, 'objects': []}
```
See the empty `objects`, while the 'Boundary01.pli' is not empty:
"
Boundary01
    3    2
6.625216613133794E+005  1.524474171041823E+006 Boundary01_0001
6.625216613133794E+005  1.524910832891534E+006 Boundary01_0002
6.625216613133794E+005  1.525410832891534E+006 Boundary01_0003
"

**Expected behavior**
Able to parse this file for the 2D boundary. 

**Suggested solution**
(by @arthurvd )
The third column of support point labels should be ignored by the parser (but NOT lead to an error). The header definition is leading: if it specifies 2 columns, then only read 2 values from each line, and silently ignore anything that's left at the end.

My motivation for this solution is: the Delft3D FM Suite currently exports with a support point label on *each* line, and we want to support all models files produced by our official release.
However, there is no need to parse and store those labels, because they are in fact ignored right now by the kernel, because frontend and backend are not using the same format currently (even though they are present in the .pli files)
This first need to be fixed in frontend+backend. Only then we will consider full support in hydrolib-core.

**Version info (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 0.4.1]

**Comment by xldeltares** [comment]
Thanks, @arthurvd and @veenstrajelmer for the explanation! Now I understand why the supported point labels are not supported by hydrolib-core. And I agree that the fix should first be the front- and back-end. 

Since the pli file without supported point labels can indeed be read back to the GUI, I think we are good off with reading/writing pli files without supported point labels in hydromt-delft3dfm. 
That means we won't support updating a model that was exported from GUI, which was acceptable. 
If this behavior would change, we will seek dfm-tools for preprocessing the pli file.

**Comment by xldeltares** [comment]
> ```
> If you got your code from some documentation, please let me/@arthurvd know so it can be updated.
> ```
Thanks! I did not get the code from the documentation, it was a small test of "Why my PolyFile object is empty" :)

**Comment by arthurvd** [comment]
Hi @xldeltares, I will re-open this issue, because I think hydrolib-core *should* support reading of boundary polylines currently produced by the FM Suite (both kernel and GUI support *reading* of pli point labels, only they are not used in the actual calculation).

**Comment by arthurvd** [comment]
Hi @xldeltares, I know that you are currently modifying boundary pli files, removing the last column with point labels.
Yet, we have fixed the support for this in hydrolib-core.
Could you pleas make some time to test the new support on your (unmodified) pli files?
The code is in:
https://github.com/Deltares/HYDROLIB-core/pull/482
Thanks!

**Comment by xldeltares** [comment]
@veenstrajelmer Thanks for picking this up!
