### ISSUE TITLE
"blockFrom" time interpolation parameter gives error in Delft3DFM

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB-core#473]
**Describe the bug**
In Enum ```hydrolib.core.dflowfm.bc.TimeInterpolation [line 80]``` 
block_from is written as the string "blockFrom". 
However, in Delft3DFM UM Section E2.3, this should be "Block-From".
Using "blockFrom" will give an error when running the model.

**Expected behavior**
It should be written as "Block-From". 

**Screenshots**
![image](https://user-images.githubusercontent.com/71022080/226851604-9acc0adc-60fc-4c45-a030-a5b5ad000631.png)

**Version info (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 0.4.1]

**Comment by tim-vd-aardweg** [comment]
`Block-To` should indeed also be updated. Will do that in this issue.
