### ISSUE TITLE
z-sigma layers not supported by FMModel

### ISSUE THREAD

**Issue by SCLaan** [Deltares/HYDROLIB-core#474]
**Describe the bug**
Currently FMModel does not support geometry keywords for (3D) z-sigma layer models. When reading a mdu, these keywords end up in the comments, but are not read correctly. When saving the model, the information is lost. Similarly, it is not possible to initialize a FMModel with z-sigma layers, because the keywords cannot be set. Keywords are:
```
> Numtopsiguniform                    = 1                                                                   # Number of sigma layers in top of z-layer model
> Dztop                               = 5.0                                                                 # Z-layer thickness of layers above level Dztopuniabovez
> Floorlevtoplay                      = -5.0                                                                # Floor level of top layer
> Dztopuniabovez                      = -100.0                                                              # Above level Dztopuniabovez layers will have uniform Dztop, SigmaGrowthFactor below this level
> Keepzlayeringatbed                  = 2                                                                   #  bedlayerthickness = zlayerthickness at bed 0 or 1
> Dxwuimin2D                          = 0.1                                                                 # Smallest fraction dx/wu , set dx > Dxwuimin2D*wu, Default = 0.1
```

**To Reproduce**
1. test = dfm.FMModel(Path(r'p:\i1000668-tcoms\03_newModel\02_simulations\02_3D\tests\A03_coarse_53sigma\SEA_3D_3km.mdu'),path_style='unix')
2. test.save(Path('test.mdu'),recurse=False)

**Expected behavior**
Output mdu should contain the same contents.
_Related to this, but a bit of a large feature request: I think all existing keywords should be available. In practice, frequently new keywords are added and then immediately used in model applications. FMModel should be able to read this and keep it in memory, so no information gets lost. I know this is against the vision for hydrolib, but it would be good to replace the current ValueError that shows with a 'ValueWarning', so a user can continue if desired._

**Version info (please complete the following information):**
 - OS: Windows 10

**Comment by priscavdsluis** [comment]
This issue is waiting on the merge for #339
