### ISSUE TITLE
Create a developers guide

### ISSUE THREAD

**Issue by tim-vd-aardweg** [Deltares/HYDROLIB-core#481]
**What is the need for this task.**
We need documentation for some common developers procedures/tasks. This documentation can also be useful for reviews.

**What is the task?**
Create a document where we can list guides and procedures for developers. Content can for example include:
- Updating the `__init__.py` files if we change the public API.
- Updating the `dhydro_support_hydrolib-core.xlsx` if new functionalities have been added.
~~- How to test new models.~~ (Should be done when we have refactored the parsers and serializers)
~~-- When do we use files for test data and when do we use in-memory data.~~

**Comment by priscavdsluis** [comment]
#16 can probably be closed with this issue.

**Comment by tim-vd-aardweg** [comment]
As discussed during the standup:
- I have removed the developers guide from the online documentation. It is now only a document that can be found in the repo.
- The initial contents will remain as is. When we overhaul the documentation, we can see if items from the `How to contribute` page can be moved to the developers guide.
- When we pick up the refactoring of the parsers and serializers (https://github.com/Deltares/HYDROLIB-core/issues/503), we should add something about how we want to test parsers and serializers.
