### ISSUE TITLE
Add support for double quoted names in the .xyn file

### ISSUE THREAD

**Issue by tim-vd-aardweg** [Deltares/HYDROLIB-core#537]
**Is your feature request related to a problem? Please describe.**
In https://github.com/Deltares/HYDROLIB-core/issues/459 support for `.xyn` files was added. As per a comment in one of the related PRs (https://github.com/Deltares/HYDROLIB-core/pull/508#issuecomment-1502927034) double quotes were not supported. However, after some experimenting by @veenstrajelmer, it seems that double quotes are in fact supported by the kernel!

**Describe the solution you'd like**
Add support for names that are surrounded by double quotes. Names surrounded by double quotes should behave the same as names surrounded by single quotes. So: names surrounded by double quotes may contain spaces. Station names may not contain `'` or `"`.

**Comment by veenstrajelmer** [comment]
Initial mention in https://github.com/Deltares/HYDROLIB-core/pull/508#issuecomment-1502927034

Suggestion (expect that FM kernel works like this, it is also Python style):
`"string met ' is goed"`
`'string met " is goed'`
`"string met " is fout"` >> `SyntaxError: EOL while scanning string literal`
`'string met ' is fout'` >> `SyntaxError: EOL while scanning string literal`

**Comment by tim-vd-aardweg** [comment]
We did some experimenting to see what happens in the kernel. We used the following `obs.xyn` file:

```
1.1 2.2 NaamMetDubbeleQuote"InHetMidden
1.1 2.2 NaamMetEnkeleQuote'InHetMidden
1.1 2.2 NaamMetTweeDubbeleQuotes""InHetMidden
1.1 2.2 NaamMetTweeSingleQuotes''InHetMidden
1.1 2.2 'SingleQuotedNaamMetDubbeleQuote"InHetMidden'
1.1 2.2 'SingleQuotedNaamMetSingleQuote'InHetMidden'
1.1 2.2 "DubbelQuotedNaamMetSingleQuote'InHetMidden"
1.1 2.2 "DubbelQuotedNaamMetDubbeleQuote"InHetMidden"
1.1 2.2 NaamMetZowelEnkele'alsDubbeleQuote"InHetMidden
1.1 2.2 NaamMetZowelEnkele''alsDubbeleQuotes""InHetMidden
```

The results are shown here:
![XYN names](https://user-images.githubusercontent.com/71257004/232458222-3e7bf7c1-55c8-4a64-8c9e-8d95d624f594.png)

So:
```
1.1 2.2 NaamMetDubbeleQuote"InHetMidden --> possible
1.1 2.2 NaamMetEnkeleQuote'InHetMidden --> *not* possible
1.1 2.2 NaamMetTweeDubbeleQuotes""InHetMidden --> possible
1.1 2.2 NaamMetTweeSingleQuotes''InHetMidden --> *not* possible
1.1 2.2 'SingleQuotedNaamMetDubbeleQuote"InHetMidden' --> possible
1.1 2.2 'SingleQuotedNaamMetSingleQuote'InHetMidden' --> ❗ The part after the second ' is ignored.
1.1 2.2 "DubbelQuotedNaamMetSingleQuote'InHetMidden" --> *not* possible
1.1 2.2 "DubbelQuotedNaamMetDubbeleQuote"InHetMidden" --> ❗ The part after the second " is ignored.
1.1 2.2 NaamMetZowelEnkele'alsDubbeleQuote"InHetMidden --> *not* possible
1.1 2.2 NaamMetZowelEnkele''alsDubbeleQuotes""InHetMidden --> *not* possible
```

Discussed the following with @veenstrajelmer:
- We will add support for double quotes while parsing. The same rules apply for single quotes and double quotes.
- Eventhough the kernel supports double quotes in the name, we will (atleast for now), not allow double quotes in the name.
- So names may not contain `'` or `"`.

I will update the issue description based on these findings.
