### ISSUE TITLE
Inconsistent keyword usage in closed property of rectangular profile

### ISSUE THREAD

**Issue by Kreef** [Deltares/HYDROLIB-core#545]
**Describe the bug**
The closed keyword in HYDROLIB-core/hydrolib/core/dflowfm/crosssection/models/RectangleCrsDef defaults to True, but D-HDYRO (v23.01) expects "yes" and "no"; as described in the user manual (Table C.24)

**Expected behavior**
write yes or no to crsdef.ini

replacing: closed: str = Field(True)
by: closed: str = Field("yes")
fixed it for me

**Comment by tim-vd-aardweg** [comment]
@rhutten I was told that if the kernel expects a boolean for a keyword they accept all values such as: `1`, `y`, `yes`, `t`, `true`, `j`, `ja` and several more. Given that the kernel can handle all these values, do you think we should still update how the `closed` keyword is written to the file?

In HYDROLIB-core we basically always write booleans as `0` or `1`.

**Comment by Kreef** [comment]
@veenstrajelmer I cannot verify the problem anymore as I am not working with D-HYDRO anymore, but this issue was not solely pointing out an inconsistency. I believe it either caused the affected profile to not be loaded in the GUI, or the DIMR set to not being loaded in the GUI.

**Comment by arthurvd** [comment]
Regarding consistency: I've decided do try and change all boolean settings in D-Flow FM to print `true` and `false` in mdu/dia/ini files, and will include the frontend development team to also try and make that change.
Backwards compatibility in kernel: old yes/no/1/0 values will still be supported for a while, but hydrolib-core can stop supporting old values in an upcoming release.

**Comment by arthurvd** [comment]
@tim-vd-aardweg : I think remaining work for hydrolib-core is to update the matching fields in the various Comments classes, for example:
```python
        closed: Optional[str] = Field("no: Open channel, yes: Closed channel.")
...
        usevolumetables: Optional[str] = Field(
            "Use volume tables for 1D grid cells (1: yes, 0 = no).",
...

**Comment by veenstrajelmer** [comment]
Follow-up issue created to update comments: https://github.com/Deltares/HYDROLIB-core/issues/673
