### ISSUE TITLE
Repeatedly creating 1D2D links results in error due to double entries

### ISSUE THREAD

**Issue by Kreef** [Deltares/HYDROLIB-core#546]
**Describe the bug**
When adding 1D2D links more than one time, for example some embedded and some later links, issues arise due to double counting of link ids. I found the issue and propose a solution below.

**To Reproduce**
within the Link1d2d class in HYDROLIB-core/hydrolib/core/dflowfm/net/models.py, the process function appends new links to exising links. The code below is currently in HYDROLIB:
    def _process(self) -> None:
        """
        Get links from meshkernel and add to the array with link administration
        """
        contacts = self.meshkernel.contacts_get()

        self.link1d2d = np.append(
            self.link1d2d,
            np.stack([contacts.mesh1d_indices, contacts.mesh2d_indices], axis=1),
            axis=0,
        )
        self.link1d2d_contact_type = np.append(
            self.link1d2d_contact_type, np.full(contacts.mesh1d_indices.size, 3)
        )
        self.link1d2d_id = np.append(
            self.link1d2d_id,
            np.array([f"{n1d:d}_{f2d:d}" for n1d, f2d in self.link1d2d]),
        )
        self.link1d2d_long_name = np.append(
            self.link1d2d_long_name,
            np.array([f"{n1d:d}_{f2d:d}" for n1d, f2d in self.link1d2d]),
        )

Here, self.link1d2d and self.link1d2d_contact_type are handled correctly. However, self.link1d2d_id and self.link1d2d_long_name take the current entries and apppend the names of all 1d2d link in self.1d2d link. As self.1d2dlink contains both the old and new entries (due to the append earlier), self.link1d2d_id will end up with double entries for all entries that were already present. This leads to errors when writing the DIMR configuration.

A solution would be to change the process function into the following, solving the issue:

    def _process(self) -> None:
        """
        Get links from meshkernel and add to the array with link administration
        """
        contacts = self.meshkernel.contacts_get()

        self.link1d2d = np.append(
            self.link1d2d,
            np.stack([contacts.mesh1d_indices, contacts.mesh2d_indices], axis=1),
            axis=0,
        )
        self.link1d2d_contact_type = np.append(
            self.link1d2d_contact_type, np.full(contacts.mesh1d_indices.size, 3)
        )

        self.link1d2d_id = np.array([f"{n1d:d}_{f2d:d}" for n1d, f2d in self.link1d2d])

        self.link1d2d_long_name = np.array([f"{n1d:d}_{f2d:d}" for n1d, f2d in self.link1d2d])

**Expected behavior**
No double counting and correctly saving the model

**Comment by veenstrajelmer** [comment]
@Kreef could you supply a minimal example to reproduce this issue? It will not be part of the next release, but still good to have this fixed. I found a linked PR with your suggestion to resolve this issue, but this is outdated by now and there are not tests added. A minimal example would help to pinpoint the issue and to check the effect of the code change. I realize it is over a year ago already, so I understand if this is not possible anymore by now.

**Comment by veenstrajelmer** [comment]
I could easily generate a testcase based on the existing test code. The linked PR solves the issue. This might be included in the next release (next week)
