### ISSUE TITLE
Reading of [sedtrails] section in .mdu

### ISSUE THREAD

**Issue by SCLaan** [Deltares/HYDROLIB-core#620]
**Describe the bug**
HYDROLIB-core 0.7.0 cannot read the default [sedtrails] section in a .mdu, as written in the copy in the .dia:
```
[sedtrails]
SedtrailsGrid       =             # Grid file for sedtrails output locations on corners
SedtrailsAnalysis   = all         # Sedtrails analysis. Should be all, transport, flowvelocity or soulsby.
SedtrailsInterval   = 3600. 0. 0. # Sedtrails output times (s), interval, starttime, stoptime (s), if starttime, stoptime are left blank, use whole simulation period
SedtrailsOutputFile =             # Sedtrails time-avgd output file
```

**To Reproduce**
1. Include the above code in a .mdu
2. Try to read the .mdu
   ```
   from pathlib import Path
   import hydrolib.core.dflowfm as hcdfm
   hcdfm.FMModel(filepath=Path(r'P:/path/to/file.mdu'), recurse=False)
   ```
5. See the error (below)

**Expected behavior**
This section should be read correctly. Alternatively it could be included in a `comments` field, as is done for the [veg] section.

**Screenshots**
```
ValidationError: 1 validation error for FMModel
mwra_hydro_dia.mdu -> sedtrails
  extra fields not permitted (type=value_error.extra)
```

**Version info (please complete the following information):**
 - OS: Windows 10
 - Version 0.7.0

**Comment by MRVermeulenDeltares** [comment]
As we understand, the goal for this issue is:
- Implement sedtrails section
- Add sedtrails section to FMModel

@veenstrajelmer & @rhutten is this correct?

**Comment by tim-vd-aardweg** [comment]
I got a very elaborate answer, I will post it here (in Dutch):

> . De lijst van keywords lijkt op zich compleet.
D-Flow FM ondersteunt de volgende keywords in het [sedtrails] blok:

> SedtrailsGrid
Standaard een lege string. Indien dit een lege string is dan is de sedtrails uitvoer niet actief en worden andere keywords niet gelezen.
Indien niet leeg dan moet dit verwijzen naar een netCDF UGRID file met een 2D rooster.

> SedtrailsAnalysis
De waarde moet een van de volgende strings zijn: all, flowvelocity, transport of soulsby.
Indien niet gespecificeerd: all.

> SedtrailsInterval
Hier worden drie getallen verwacht: interval, start time, end time.
Het eerste getal (interval) wordt in de code begrensd op getallen groter of gelijk aan dt_user.
De default waarden zijn 3600 0 0

> SedtrailsOutputFile
Dit is de naam van de extra netCDF UGRID map uitvoer.
Default wordt deze naam gelijk gesteld aan <case>_sedtrails.nc waarbij <case> de naam is van de mdu-file.

>De optie maakt het mogelijk om enkele D-Flow FM grootheden weg te schrijven gemiddeld naar de nodes van het gespecificeerde rooster:
•	dieptegemiddelde stroomsnelheden (indien flowvelocity of all)
•	bodem en zwevende sediment transporten (indien transport of all)
•	waterdiepte, bodemschuifspanning, en niet-lineaire snelheidsbijdrage van golven (indien soulsby of all)
Hoewel deze functionaliteit primair is ontwikkeld voor nabewerking met de Sedtrails tool ten behoeve van het opstellen van sedimentbalansen, weet ik dat andere collega’s ook geïnteresseerd zijn in deze optie omdat grootheden hiermee op een ander (kleiner) rooster kan worden weggeschreven hetgeen een vermindering van de dataopslag zou kunnen geven. Ik zie hiervoor op termijn liever een andere oplossing.

**Comment by veenstrajelmer** [comment]
@SCLaan I assume you do not use this section yourself, but you just noticed in the diafile, correct? I have not seen this section in diafiles recently. Do you have an example where it does show up (including a dimrset version number)? It might be removed from the standard diafile? The `[sedtrails]` section is not documented in the manual and if it is then also not outputted to the diafile and you do not use it, I am a bit in doubt whether we should pick this up now.

**Comment by SCLaan** [comment]
Recently Julien made quite some changes to the .dia. Some input, such as the [sedtrails]-section doesn't show anymore, unless users place it in the .mdu. Juliens changes:
- https://issuetracker.deltares.nl/browse/UNST-3300
- https://issuetracker.deltares.nl/browse/UNST-7437
- https://git.deltares.nl/oss/delft3d/-/merge_requests/489

My reason to open this issue was that I (and others) often copy the .dia as a starting point of a new .mdu to have the latest overview of keywords. With this change this will no longer cause a problem. It will however still be a problem for users that do use sedtrails.

I guess the broader point is that right now HYDROLIB-core cannot handle unknown sections. Unknown keywords are caught in the comments, but newly added sections cause a validation error.
- **Would it be an idea to also catch unknown sections as comments and just raise a warning?**
- And maybe a separate issue: Right now if you load an mdu with keywords unknown to HYDROLIB-core, these are read, but stored as comments. If you then save that same mdu again, the information is lost and the model settings have effectively changed. I don't think this is desired behavior! Is there a way to also save these unknown keywords, even if they are not in HYDROLIB-core's database?
