### ISSUE TITLE
Don't write keywords with a None value to the files

### ISSUE THREAD

**Issue by tim-vd-aardweg** [Deltares/HYDROLIB-core#661]
Until now, I thought that if a keywords is Optional and has a None value, that HYDROLIB-core would not write these keywords to the mdu file. However, recently we have added a lot of new research keywords that are all optional and have a default value of None. It turns out that if the user uses one research keywords, then all new research keywords will be written the mdu file. This is unwanted behaviour.

We then checked the behaviour for non-research keywords and we found that there are still a lot of regular keywords that do not have a default value. That problem will be tackled in #648. 

In this issue we will change that HYDROLIB-core will no longer write keywords with a None value to the MDU file. The exception is for FileModels as they can't have a default value.

**Comment by veenstrajelmer** [comment]
To avoid that non-research keywords are not printed to the mdu, I looked up the default values in the FM kernel code for the keywords for which HYDROLIB-core sets `None` as a default.

```
Numerics > Comments > qhrelax: "Relaxation on Q-h open boundaries" (keyword not present in *.f90 files, deprecated?)
Numerics > fixedweirtopfrictcoef: -999 (src/dflowfm_data/m_flowparameters.f90)
Physics > itcap: 0 (src/dflowfm_data/m_flowparameters.f90)
Time > autotimestep: 1 (difficult to find in code, seems to be ja_timestep_auto in src/dflowfm_data/m_flowtimes.f90)
Time > startdatetime: ' ' (src/dflowfm_data/m_flowtimes.f90)
Time > stopdatetime: ' ' (src/dflowfm_data/m_flowtimes.f90)
Restart > restartdatetime: ' ' (src/dflowfm_data/m_flowtimes.f90)
ExternalForcing > rainfall: 0 (guessed, too much search results)
ExternalForcing > qext: 0 (guessed, no search results)
ExternalForcing > evaporation: 0 (guessed, too much search results)
ExternalForcing > windext: None (wind should come via the ext file, this keyword should be deprecated one day I think) >>??
Trachytopes > trtmxr: 8 (md_mxrtrach in src/dflowfm_data/unstruc_model.f90)
Geometry > Comments uniformwidth1d: "Uniform width for channel profiles not specified by profloc" (src/dflowfm_data/unstruc_model.f90)
Geometry > uniformwidth1d: 2 (wu1DUNI in src/dflowfm_data/m_flowgeom.f90)
Geometry > dztop: -999 (src/dflowfm_data/m_flow.f90)
Geometry > floorlevtoplay: -999 (src/dflowfm_data/m_flow.f90)
Geometry > dztopuniabovez: -999 (src/dflowfm_data/m_flow.f90)
Groundwater > Comments > groundwater: "0=No (horizontal) groundwater flow, 1=With groundwater flow"
Groundwater > Comments > hinterceptionlayer: "Intercept this amount of rain (m)"
Groundwater > hinterceptionlayer: None? (no default value set)
Groundwater > bgrwuni: -999 (src/dflowfm_data/m_grw.f90)
Groundwater > sgrwini: -999 (src/dflowfm_data/m_grw.f90)
Processes > Comments > dtmassbalance: "waq mass balance output time step" >> deprecated keyword according to src/dflowfm_data/fm_deprecated_keywords.f90 
```

filepaths (indirectly in src/dflowfm_data/unstruc_model.f90)
should None not be replaced with this, just like for flowgeomfile and many others?
	`default_factory=lambda: DiskOnlyFileModel(None)`
```
ExternalForcing > extforcefile (md_extfile)
ExternalForcing > extforcefilenew (md_extfile_new)
Trachytopes > trtdef: 
Trachytopes > trtl: 
Output > outputdir: 
Output > waqoutputdir: 
Output > obsfile: 
Output > crsfile: 
Geometry > bathymetryfile:
Geometry > inifieldfile:
Geometry > thindamfile: 
Geometry > fixedweirfile: 
Geometry > pillarfile: 
Geometry > vertplizfile: 
Geometry > frictfile: 
Geometry > crossdeffile: 
Geometry > crosslocfile: 
Geometry > storagenodefile: 
Geometry > partitionfile: 
Geometry > gridenclosurefile:
Geometry > roofsfile:
Geometry > gulliesfile:
Particles > particlesfile:
```

**Comment by veenstrajelmer** [comment]
After the implementation in #663, there are still some errors generated by hydrolib core:
- two keywords are in the FM code, but not yet in hydrolib-core. These were incorrectly marked as deprecated AFAIK
- several keywords are deprecated, it would be nice to mention this separately, follow-up issue created in https://github.com/Deltares/HYDROLIB-core/issues/668

**Missing keywords**
- jadelvappos (int, 0) (from src/dflowfm_data/m_physcoef.f90)
- umodlin (float, 1.0) (from src/dflowfm_data/m_physcoef.f90)
