### ISSUE TITLE
Improve logged warnings for several ini block keywords

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#70]
The validation of some ini-based models currently is lacking warnings, or has too simple warnings logged.
**For structures:**
"Couldn't derive specific type of Structure"
is lacking id and given type of the actual structure.

**For bc data blocks:**
when checking field "function" no error is given at all.

**Comment by priscavdsluis** [comment]
The mentioned issues were already solved in a different issue it seems. I have added some overrides for the `_get_identifier` function.
