### ISSUE TITLE
Create dimr parser (.xml)

### ISSUE THREAD

**Issue by evetion** [Deltares/HYDROLIB-core#8]
Or at least class that can create that hard-coded mdu start.

**Comment by arthurvd** [comment]
@priscavdsluis : Adri Mourits just confirmed that this is indeed the official xsd for dimr config files:
http://content.oss.deltares.nl/schemas/dimr-1.3.xsd
I recommend supporting 1.3 (as it is backwards compatible with 1.2 and earlier versions.
