### ISSUE TITLE
Improve non-support+warning for duplicate keys

### ISSUE THREAD

**Issue by arthurvd** [Deltares/HYDROLIB-core#92]
When an MDU file contains duplicate key names, a confusing exception occurs:
Example code:
```
modelroot = Path('d:/dam_ar/dflowfm_models/HYDROLIB/MGB_FMonly/fm/')
mdufile = 'moergestels_broek.mdu'
fm = FMModel(filepath = modelroot / mdufile)
```

Relevant piece of MDU:
```
AngLat                            = 0.                  # Angle of latitude S-N (deg), 0: no Coriolis
AngLon                            = 0.                  # Angle of longitude E-W (deg), 0: Greenwich, used in solar heat flux computation.
AngLat                            = 1.  # duplicate!
```
Resulting Exception:
```
Exception has occurred: ValidationError       (note: full exception trace is shown but execution is paused at: <module>)
1 validation error for FMModel
moergestels_broek.mdu -> geometry -> AngLat
  value is not a valid float (type=type_error.float)
  File "C:\checkouts\HYDROLIB-core_git\hydrolib\core\basemodel.py", line 53, in __init__
    super().__init__(**data)
```

The **data contains a list value for the duplicate input (often `[None, None]` if both were empty), but it depends on the Field's datatype what kind of validation error is given.
For example for this field:
```
    waterlevinifile: Optional[Path] = Field(None, alias="waterLevIniFile")
```
the error when passing duplicate lines in input is:
```
geometry -> waterLevIniFile
  value is not a valid path (type=type_error.path)
```

When doing the same for a model class type, e.g.:
```
    crosslocfile: Optional[CrossLocModel] = Field(None, alias="crossLocFile")
    partitionfile: Optional[PolyFile] = Field(None, alias="partitionFile")
```
the error when passing duplicate lines in input is:
```
geometry -> crossLocFile
  value is not a valid dict (type=type_error.dict)

geometry -> partitionFile
  value is not a valid dict (type=type_error.dict)
```

Duplicate keys should be marked as invalid, but with a more sensible validation error.
Where can we catch this validation error and improve the message?

**Comment by evetion** [comment]
@arthurvd What do you think of:

```
E               moergestels_broek.mdu -> geometry -> partitionFile
E                 value is not a valid dict. The key partitionFile might be duplicated in the input file.
```

**Comment by arthurvd** [comment]
> @arthurvd What do you think of:
> 
> ```
> E               moergestels_broek.mdu -> geometry -> partitionFile
> E                 value is not a valid dict. The key partitionFile might be duplicated in the input file.
> ```

Yes, perfectly fine,  I just didn't know where to implement that.
